### ISSUE TITLE
Add Rate Limiting

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#10]

**Comment by ageddesi** [comment]
Rate limiting is used to control how many requests a given consumer can send to the API.

To tell your API users how many requests they have left, set the following headers:

X-Rate-Limit-Limit, the number of requests allowed in a given time interval
X-Rate-Limit-Remaining, the number of requests remaining in the same interval,
X-Rate-Limit-Reset, the time when the rate limit will be reset.

**Comment by ageddesi** [comment]
https://www.geeksforgeeks.org/what-is-express-rate-limit-in-node-js/

**Comment by ageddesi** [comment]
Rate Limit
Requests through the API are rate limited per IP Location. Current rate limits:

1,000 requests per hour
50 requests per minute (5% of the hourly total)

Once you exceed either limit, you will be rate limited until the next cycle starts. Space out any requests that you would otherwise issue in bursts for the best results.

The rate limiting information is contained within the response headers of each request. The relevant headers are:

RateLimit-Limit: The number of requests that can be made per hour.
RateLimit-Remaining: The number of requests that remain before you hit your request limit. See the information below for how the request limits expire.
RateLimit-Reset: This represents the time when the oldest request will expire. The value is given in [Unix epoch time](http://en.wikipedia.org/wiki/Unix_time). See below for more information about how request limits expire.
As long as the RateLimit-Remaining count is above zero, you will be able to make additional requests.

The way that a request expires and is removed from the current limit count is important to understand. Rather than counting all of the requests for an hour and resetting the RateLimit-Remaining value at the end of the hour, each request instead has its own timer.

This means that each request contributes toward the RateLimit-Remaining count for one complete hour after the request is made. When that request's timer runs out, it is no longer counted towards the request limit.

This has implications on the meaning of the RateLimit-Reset header as well. Because the entire rate limit is not reset at one time, the value of this header is set to the time when the oldest request will expire.

Keep this in mind if you see your RateLimit-Reset value change, but not move an entire hour into the future.

If the RateLimit-Remaining reaches zero, subsequent requests will receive a 429 error code until the request reset has been reached. You can see the format of the response in the examples.


Sample Rate Limit Headers
```
    RateLimit-Limit: 1200
    RateLimit-Remaining: 1193
    RateLimit-Reset: 1402425459

```
Sample Rate Exceeded Response
```
    429 Too Many Requests
    {
            id: "too_many_requests",
            message: "API Rate limit exceeded."
    }
```

**Comment by Vishwamagdavan** [comment]
Hi @ageddesi, Please assign me this task; I'd like to do it.

**Comment by ageddesi** [comment]
Hi @Vishwamagdavan that would be great thank you. Please can you make sure the limits can be configured via the .env file. 👍 Good luck, if you need any help message me here or join us on discord. https://discord.gg/WEtvwvQ7
