### ISSUE TITLE
[OpenAPI] - BankFeed API Endpoints

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#102]
The bankfeed api endpoints need open api comments added

**Comment by siddharth1729** [comment]
Hii @ageddesi  pleas assign this to me 

and also please elplain a bit more about this

**Comment by ageddesi** [comment]
Hi @siddharth1729 if you look at branch v.0.13.0 where the latest code lives you will see that other endpoints have OpenAPI comments within the api routes files. The task for this is to update the bank-feeds api route file to have its comments added.

**Comment by siddharth1729** [comment]
ok means i have to properly comment he bankfeed api like other is dne in the project ?

**Comment by ageddesi** [comment]
Yes please, that would be ace. We use this to auto generate the swagger file now.
