### ISSUE TITLE
[Tests] - Color Module

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#104]
The Color module needs tests added

**Comment by computamike** [comment]
adding tests might be something I could have a go at - will give it a go.

**Comment by ageddesi** [comment]
@computamike Thanks mike. There is plenty of examples in the project now. Please branch from v.0.13.0 for the latest code base. 
If you need any help just ask on here or on our discord. https://discord.gg/yxqrkjDR87
