### ISSUE TITLE
[OpenAPI] - Ecommerce API Endpoints

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#105]
The ecommerce api endpoints need OpenAPI comments added for documentation

**Comment by AnishDe12020** [comment]
I would like to take up this issue, can you please assign it to me?

**Comment by ageddesi** [comment]
Thank you @AnishDe12020 this is now assigned to you.

**Comment by ageddesi** [comment]
Please branch from v.0.13.0 for the latest code base, if you need help just leave a comment here or join us on discord https://discord.gg/6UaxgtsM 👍

**Comment by AnishDe12020** [comment]
Seems like both the ecommerce routes have the same functionality (the second one takes in a quantity as a parameter)

https://github.com/ageddesi/Mocked-API/blob/a5311f6649dd94222e6f49fc1f847093fcf75320/modules/ecommerce/api/ecommerce-routes.ts#L8-L18

Should I add the functionality in the second route to return a list of carts of the given quantity?
