### ISSUE TITLE
[Tests] - Ecommerce Module

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#106]
The ecommerce modules needs tests adding

**Comment by edwardsmoses** [comment]
Hello, 
I'll like to work on this. Could I get assigned? 
Thanks.

**Comment by edwardsmoses** [comment]
Hello, 
For this endpoint, I noticed that the openapi definitions are different from what the endpoint returns. 
Should I update the openapi definitions or update the endpoint to return what the openapi definitions specify? 

Thanks.

**Comment by ageddesi** [comment]
Hi @edwardsmoses, thank you for the tests you added, If you want to do another pull for updating the OpenAPI definitions. I would really appreciate the help. 👍

**Comment by edwardsmoses** [comment]
Hi @ageddesi , 
Thanks - I'll get on updating the OpenAPI definitions.

**Comment by bikrantjajware** [comment]
Hello @ageddesi , 
is this issue resolved, if not i would like to contribute on this.

**Comment by ageddesi** [comment]
The ticket seems to be open still so please feel free to tackle this.

**Comment by bikrantjajware** [comment]
Thanks  @ageddesi , could you assign me this issue, i'll submit a PR. Also  one question does this count as a hacktoberfest contribution
