### ISSUE TITLE
[OpenAPI] - Music API Endpoints

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#112]
The music api endpoints need OpenAPI comments for documentation

**Comment by ATH42** [comment]
i'd love to help out. Do you have a reference on how you want this?

**Comment by ATH42** [comment]
if my referenced PR is what was needed here, i'd be happy to tackle all other open api documentation tickets.

**Comment by ageddesi** [comment]
Thank you @ATH42 That was perfect. 👍
