### ISSUE TITLE
Running a local instance of Mocked-API (swagger) still calls the main https://api.mocked-api.dev address

### ISSUE THREAD

**Issue by computamike** [ageddesi/Mocked-API#114]
**Describe the bug**
Running a local instance of Mocked-API (swagger) still calls the main https://api.mocked-api.dev address, sending network traffic to https://api.mocked-api.dev rather than http://localhost:3000 address (using the Swagger Interface).

**To Reproduce**
1. Clone main branch
2. Install dependencies `npm install`
3. Start the site `npm run serve`
4. site is served on port 3000
5. load localhost:3000 in browser (in this case : edge) - 
6. See that request is sent to api.mocked-api-dev (and experienced a CORS error)

**Expected behavior**
I would expect that a local running swagger instance should point it itself allowing developers to test APIs locally.

**Screenshots**
![image](https://user-images.githubusercontent.com/464876/193478438-e009d826-0cd5-4462-82b9-790bc26b465d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (21H2 19044.1826)
 - Browser MS edge
 - Version 105.0.1343.50 (Official build) (64-bit)

**Additional context**
I think this might be resolved by looking at configuration settings

**Comment by computamike** [comment]
Had a quick look - I think we can create a .env.example file with a host setting in (localhost:3000)  - and use that along with a fallback of "api.mocked-api.dev", meaning that if you deploy this code to a server without the .env file, then  host is "api.mocked-api.dev" - but if you have a .env file, then that host value is used instead.

The .env.example can be set up with localhost:3000 as the host setting.  When checking out the code, the developer copies .env.example to .env (we also add a .gitignore for .env) and now when loading it should work locally.

Will test this locally - but the thing I don't like about this sort of solution is that it's an extra thing a developer working on this codebase would have to do (admittedly this would potentially only affect the swagger interface).  I'd much rather a developer working on this be able to check out the code and it works.

A .env.example file is a technique I have seen before (mostly on laravel and AdonisJS based solutions) - but the infrastructure seems to be inplace for this - there is already dotenv installed.

**Comment by computamike** [comment]
ok - I have submitted a PR for this #116

**Comment by ageddesi** [comment]
Thanks @computamike 👍
