### ISSUE TITLE
[Tests] - Phone numbers module

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#120]
The phone numbers module need tests added.

**Comment by Suraj-Bhandarkar-S** [comment]
Hi, So test here means test cases for the api in use right ?  

-  To create a test case for the api to check if the returned values are correct ?

**Comment by ageddesi** [comment]
That is correct @Suraj-Bhandarkar-S and if those api return failure states those are also tested. Their is examples in the codebase already you can look at for help.

**Comment by Suraj-Bhandarkar-S** [comment]
Great thanks will look it up :)

**Comment by Suraj-Bhandarkar-S** [comment]
Also, I am not able to find the phone number module could you please confirm?

**Comment by ageddesi** [comment]
All the latest is on branch v.0.13.0 sorry I forgot to mention to Branch from there. Also if you need any help feel free to message here or on our discord channel. https://discord.gg/6UaxgtsM

**Comment by computamike** [comment]
Can this issue be closed now?

**Comment by ageddesi** [comment]
Thanks @computamike, It was suppose to be lol 👍
