### ISSUE TITLE
Define and clean up folder/files names

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#121]
At the moment the files and folders are using different naming conventions and case types.
- [ ] - Define the standards
- [ ] - Update the contribution guide to include these standards
- [ ] - Update existing folders and files to be inline.

![image](https://user-images.githubusercontent.com/1301564/193517054-68a18eb3-df0e-4579-a4a9-77621771b7be.png)
![image](https://user-images.githubusercontent.com/1301564/193517096-6159eb89-ef4a-4fa9-8181-f2f2f53f6451.png)

**Comment by fms12** [comment]
can you assign me this

**Comment by ageddesi** [comment]
Hi @fms12 Feel free to start the discussion on this post about what standards we should follow and once we all agree you can do the work involved.

**Comment by fms12** [comment]
we can add modules name like  that "chat-module" and for files, we can just like that  "CurrencyRouters"

**Comment by amanksingh99** [comment]
I can work on this if it is not assigned to anyone.
After going through the codebase I would suggest keeping **kebab-case** as the naming convention for both files and folders as this is a nodejs project.

**Comment by ageddesi** [comment]
Does anyone know of a good coding standards doc we can reference for node projects.

**Comment by fms12** [comment]
https://nodejs.dev/en/learn/ you can use this one also.

**Comment by amanksingh99** [comment]
@ageddesi https://stackoverflow.com/questions/18927298/node-js-project-naming-conventions-for-files-folders the first two answers.

**Comment by sherlyfebrianti96** [comment]
Hi is it okay if i do this work?

I would like to propose this : 
- Using PascalCase for the folders, and keep the naming simple
  - e.g : 
    - time_zones -> Timezones
    - phone-numbers -> Phones
- Using PascalCase for the filenames
- Restructuring the files
  - **Before :** 
    - Modules
      - Address/animal/etc (not-standardized yet)
        - api
          - file-routes.ts (not-standardized yet)
        - const
          - file.ts (not-standardized yet)
        - test
          - file.test.ts (not-standardized yet)
        - utils
          - file.ts (not-standardized yet)
  - **After :** 
    - Modules
      - Address/Animal/Timezones (PascalCase)
        - Address/Animal/Timezones.routes.ts (PascalCase) -> This is for APIs
        - Address/Animal/Timezones.types.ts (PascalCase) -> This is for Interfaces/Types
        - Utils (PascalCase)
          - UtilName1.ts (PascalCase)
          - UtilName2.ts (PascalCase)
        - Test
          - Address/Animal/Timezones.test.ts
          - Utils
            - UtilName1.test.ts (PascalCase) -> we can say the structure is SameAsStructureInUtils.test.ts
            - UtilName2.test.ts (PascalCase)

So in general, this is how to identify the code : 
- `*.routes.ts` is for the APIs
- `*.types.ts` is for the Interfaces and Types
- `Utils/*.ts` is for all the utilities
- The `Test` folder should have the same structure with current directory
  - and `*/\.test.ts` is for all test files

**Comment by sherlyfebrianti96** [comment]
Hi is it okay if i do this work?

I would like to propose this : 
- Using kebab-case for the folders, and keep the naming simple
  - e.g : 
    - time_zones -> timezones
    - phone-numbers -> phones
- Using kebab-case for the filenames
- Restructuring the files
  - **Before :** 
    - Modules
      - Address/animal/etc (not-standardized yet)
        - api
          - file-routes.ts (not-standardized yet)
        - const
          - file.ts (not-standardized yet)
        - test
          - file.test.ts (not-standardized yet)
        - utils
          - file.ts (not-standardized yet)
  - **After :** 
    - Modules
      - address/animal/timezones (kebab-case)
        - address/animal/timezones.routes.ts (kebab-case) -> This is for APIs
        - address/animal/timezones.types.ts (kebab-case) -> This is for Interfaces/Types
        - utils (kebab-case)
          - util-name-1.ts (kebab-case)
          - util-name-2.ts (kebab-case)
        - test
          - address/animal/timezones
          - utils
            - util-name-1.test.ts (kebab-case)
            - util-name-2.test.ts (kebab-case)

So in general, this is how to identify the code : 
- `*.routes.ts` is for the APIs
- `*.types.ts` is for the Interfaces and Types
- `utils/*.ts` is for all the utilities
- The `test` folder should have the same structure with current directory
  - and `*/\.test.ts` is for all test files

**Comment by ageddesi** [comment]
Hi @sherlyfebrianti96 I am happy with the changes you have mentioned and what we have discussed in Discord. Please feel free to take this ticket on 👍

**Comment by sherlyfebrianti96** [comment]
**Update :** 

The Interfaces/Types will be treated the same as `utils` folder.
So it will be : 

- Modules
  - address/animal/timezones (kebab-case)
    - address/animal/timezones.routes.ts (kebab-case) -> This is for APIs
    - models (kebab-case)
      - address/animal/timezones.types.ts (kebab-case)  -> This is for Interfaces/Types
    - utils (kebab-case)
      - util-name-1.ts (kebab-case)
      - util-name-2.ts (kebab-case)
    - test
      - address/animal/timezones
      - utils
        - util-name-1.test.ts (kebab-case)
        - util-name-2.test.ts (kebab-case)

**Comment by sherlyfebrianti96** [comment]
https://github.com/ageddesi/Mocked-API/pull/222
