### ISSUE TITLE
[Tests] - Timezones Module

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#127]
The timezones module is missing tests

**Comment by Kanika2772002** [comment]
hey , thrilled to contribute over there , @ageddesi can u assign me

**Comment by ageddesi** [comment]
Hey @Kanika2772002 this is all yours, welcome to the party 👍

**Comment by pjunior94** [comment]
Hello @ageddesi, may I help with something here? 👍🏻
