### ISSUE TITLE
Node.js 12.x is EOL'ed Upgrade to 16.x

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#129]
This is in relation to our docker file. 

        Node.js 12.x is EOL'ed  I'd change this to 16.x
https://nodejs.dev/en/download/

_Originally posted by @benhalverson in https://github.com/ageddesi/Mocked-API/pull/72#discussion_r985304443_

**Comment by computamike** [comment]
Current node supported versions are [here](https://github.com/nodejs/release#release-schedule) 

Additionally, we can specify supported node version in the package,json file - which might be beneficial.

**Comment by ageddesi** [comment]
We should do that :), Will mark this ticket as open for people to claim

**Comment by benhalverson** [comment]
I have this ready but the Dockerfile doesn't exist in the main branch yet. Do you want me to branch of the `v.0.13.0` branch

**Comment by ageddesi** [comment]
hi @benhalverson yes please v.0.13.0 is our current main branch
