### ISSUE TITLE
Setup dev branch

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#135]
once branch v0.13.0 is released. Set up a new branch to be the main branch called 'dev' then use only 'main' to be the branch that is deployed.

**Comment by fms12** [comment]
can you assign it to me? please tell me how can I do this because I'm new to it

**Comment by sherlyfebrianti96** [comment]
Is this task still valid? because i saw the current repository has been using 'dev' branch as default.

**Comment by ageddesi** [comment]
Hi @sherlyfebrianti96, sorry this should have been closed lol. Thanks
