### ISSUE TITLE
Add Qty Limits

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#137]
In order to protect the system from someone just saying give me 1million results and killing the API, we should add a max qty to the getQtyFromRequest function used by the endpoints. 

I say for the first instance we set this to only 100 and see how that goes.

**Comment by siddharth1729** [comment]
@ageddesi 

I this kind of paginated api ?

pleas assign this to me

**Comment by ageddesi** [comment]
@siddharth1729 there is no pagination as its random data. Just the limit is needed adding.

**Comment by vaibhavg20comp** [comment]
Can I work on this issue ?

**Comment by vaibhavg20comp** [comment]
I have made a PR regarding this #142
