### ISSUE TITLE
[New Mock] - Blockchain

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#14]
This needs to be defined, but would like to start with the following.

- Bitcoin
- Etherium

**Comment by tzii** [comment]
Can you describe this mock in more detail?

**Comment by ageddesi** [comment]
hi @tzii we need to flesh it out. But for example. https://etherscan.io/ Has lists that display latest blocks, latest transactions etc. It would be good to make fake end points for them.

**Comment by cweave** [comment]
I'll add some for XRP (Ripple) https://xrpscan.com/

Add one to get a list of random validated ledgers and a view of a transaction

**Comment by ageddesi** [comment]
@cweave That is awesome :) Thank you
