### ISSUE TITLE
[New Mock] - Social Feed

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#15]
Need to create a fake social feeds. We can do one PR per social event

- [ ] Facebook
- [x]  Instagram
- [x] Twitter

We still need to also decide what info needs to be mocked.

**Comment by YasiOnFire** [comment]
I'm happy to do `/socials/twitter`

What are your thoughts on:
```json
[
 {
	"handle": "@UserName",
	"message": "Lorem ipsum dolor sit amet consecteur",
	"media": "https://video_or_image.webm",
	"likes": 2342,
	"comments": 31,
	"retweets": 2,
	"date": "2022-09-22T16:03:17.885Z"
 }
]
```

**Comment by ageddesi** [comment]
@YasiOnFire That is great

**Comment by kalwabed** [comment]
Will work in Instagram API. I started with the API post.

**Comment by RizkyRajitha** [comment]
hi @ageddesi i would like to work on Facebook api
