### ISSUE TITLE
[New Mock] - Chat Feed

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#16]
I have just introduced a new chat endpoint in version v.0.11.0 , However I would like to extend this to include an endpoint that is not random data but instead a mocked real conversation.
Maybe we could look into generating a conversation between two bots :)

**Comment by ageddesi** [comment]
I have just introduced a new chat endpoint in version v.0.11.0 , However I would like to extend this to include an endpoint that is not random data but instead a mocked real conversation. 
Maybe we could look into generating a conversation between two bots :)

**Comment by nibih** [comment]
could you explain a bit more about what you mean by generating a conversation between two bots?

**Comment by ageddesi** [comment]
At the moment we have a chat endpoint that returns messages that are random strings. 

I was thinking as an experiment of playing around with AI was to create a chat bot and then get 2 versions of it to chat for a little while and see what the output would be, then if any good I would use it as a real mocked data version of the endpoint.

**Comment by nibih** [comment]
i think it would be more useful to have random strings of various lengths, ranging from 1 word to a whole paragraph. so that users can see if their chat system is accommodating to both short and long chats

**Comment by ageddesi** [comment]
@nibih that could be interesting.

**Comment by timothee-durand** [comment]
Hello,
 i'd like to work on that, could I get assigned ? 
Thanks !

**Comment by ageddesi** [comment]
Hi @timothee-durand this is yours. 👍 If you need any help message here or join us on discord. https://discord.gg/WEtvwvQ7

**Comment by timothee-durand** [comment]
Ok thanks !
