### ISSUE TITLE
Add a coordinates endpoint 

### ISSUE THREAD

**Issue by mdfarhaan** [ageddesi/Mocked-API#164]
**Is your feature request related to a problem? Please describe.**
A coordinates endpoint that returns a list of coordinates in the real world.
  
**Describe the solution you'd like**
Create an endpoint /coordinates which generates coordinates related entries.

**Comment by ageddesi** [comment]
This is a great idea. :) we could have multiple end points

/location/co-ordinates/random/:qty
/location/co-ordinates/country/:qty

**Comment by mdfarhaan** [comment]
I would like to take this. Can you assign it to me.

**Comment by ageddesi** [comment]
This is all yours @mdfarhaan
