### ISSUE TITLE
[New Mock] - Email Feed

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#17]
We will need a mock endpoint that returns fake email inbox of data. 

A bunch of mocked data with (we can expand as we feel is needed)

- ID
- Date Sent
- Sender Email
- Read / Unread Status
- Subject Line
- Email Content
- Tags

**Comment by YasiOnFire** [comment]
May I work on this one?

**Comment by ageddesi** [comment]
Hi @YasiOnFire Absolutely :)
