### ISSUE TITLE
Add tests for quotes module

### ISSUE THREAD

**Issue by devvspaces** [ageddesi/Mocked-API#176]
**Is your feature request related to a problem? Please describe.**
The Quotes module does not have tests for it

**Describe the solution you'd like**
I would love to write the tests for the quotes module.

**Comment by devvspaces** [comment]
hi @ageddesi , please can you assign me this?

**Comment by ageddesi** [comment]
Hi @devvspaces This ticket already exists. You can leave a message on there to see if the current assignee is still working on it. https://github.com/ageddesi/Mocked-API/issues/124
