### ISSUE TITLE
[New Mock] - Reviews

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#18]
1. Add more real worded reviews for  a series of fake products. eg. A Gaming Sports drink, a new dvd player etc. (The more we do the merrier)
2. Add fake worded reviews for a fake product using faker.lorem.sentence the same way we do in getRandomChat

**Comment by ageddesi** [comment]
Added two new endpoints in version 0.10.0

I have currently only added 5 fake reviews for a gaming sports drink. Need to make a few more categories and products so there is more options avaliable.

**Comment by Vishwak-Kiran** [comment]
I can take up this issue. How many products and its reviews do you need tho?

**Comment by ageddesi** [comment]
Hi @Vishwak-Kiran . As with our other endpoints we can allow the user to define the qty.  Please see chat api endpoints as example.

Please branch from v.0.12.0

**Comment by janetthieu** [comment]
Hi @ageddesi, I'd like to contribute to this.

**Comment by ageddesi** [comment]
Hi @janetthieu it's all yours. :)

**Comment by lsheltonSTO** [comment]
Hi @ageddesi , do you need more contributions to this for Hacktoberfest?

**Comment by lsheltonSTO** [comment]
I'm still very much a rookie at this but I used to teach English so I can come up with a bunch of nonsense if you have something to assign to me @ageddesi !

**Comment by ageddesi** [comment]
That sounds awesome. Feel free to take a crack at this ticket. :) the more
fun and real they sound the better as atm they will be random Latin
strings. :(

**Comment by lsheltonSTO** [comment]
Well, I also took 2 years of Latin in high school ;)

**Comment by ageddesi** [comment]
Haha, well your fully setup for this kind of work then lol.

**Comment by lsheltonSTO** [comment]
Are you looking for more fake reviews on the one product, or more products with their own fake reviews/categories/etc?

**Comment by ageddesi** [comment]
I am looking to expand to a variety of products and fake reviews. The more
the merrier, so will be keeping this ticket open for a long time I imagine.

**Comment by jonathlan** [comment]
Hello !

I'm new to hacktoberfest and should be able to help with this too.

Just to clarify, we need to add more reviews to this file `modules/products/data/product-reviews.ts` ?
Does the language matter?

Thanks !

**Comment by ageddesi** [comment]
Welcome @, yes more are welcome. We do jot have other languages yet. But want to open that up soon.

**Comment by jonathlan** [comment]
Great, I will share a few in English then.
Awesome project, btw!

**Comment by azulverdosa** [comment]
Hi there @ageddesi ,

Another newby looking to help out! I see you're looking for new products, with fake reviews, added to this file: modules/products/data/product-reviews.ts . Anything else to mention?

Thanks!

**Comment by ageddesi** [comment]
Yerp feel free to add more. Either same products or new.

**Comment by Mjcloclo79** [comment]
> 1. Add more real worded reviews for  a series of fake products. eg. A Gaming Sports drink, a new dvd player etc. (The more we do the merrier)
> 2. Add fake worded reviews for a fake product using faker.lorem.sentence the same way we do in getRandomChat
