### ISSUE TITLE
status endpoint update

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#180]
I would like it so that we add to new values to the status endpoint.

totalCategories : this is the total number of categories (apis)
totalEndpoints: this is the the total number of endpoints in total within the categories

**Comment by devvspaces** [comment]
hi @ageddesi , i would like to do this, can you assign me

**Comment by ageddesi** [comment]
Hey @devvspaces This is all yours, welcome to the party 💯

**Comment by devvspaces** [comment]
thanks, i will get to it

**Comment by ageddesi** [comment]
Thanks for the work on this @devvspaces 👍
