### ISSUE TITLE
Use Faker.unique

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#19]
Based on feedback in the Faker.js discord channel. We should consider updating our calls to use faker.unique instead.

**Comment by MiTo0o** [comment]
[unique](https://fakerjs.dev/api/unique.html) seems to be deprecated

**Comment by ageddesi** [comment]
Aha thank you @MiTo0o for noticing that. :)

**Comment by ageddesi** [comment]
https://github.com/all-contributors please add @MiTo0o for question
