### ISSUE TITLE
Update Address endpoint to return an Address Object

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#199]
Currently the address returned is a string and not an Object.

**Comment by devrrior** [comment]
Hi, if it doesn't bother you, could you assign me this issue? Thanks

**Comment by ageddesi** [comment]
Hi, this one is already in progress. Sorry

**Comment by devrrior** [comment]
> Hi, this one is already in progress. Sorry  

No problem. I’ll keep waiting for new issues 😃
