### ISSUE TITLE
[BUG] - Fix Duplicated Entries

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#20]
Reintroduce new set at end of this function to prevent duplicated entries
modules/animal/utils/getSpeciesOfAnimal.ts

**Comment by ageddesi** [comment]
We changed this to return data using fakers built in Unique. However it worked better when it was just using a new Set at the end of the function to remove duplicates

**Comment by ahmedsilat44** [comment]
Hey @ageddesi I would like to work on this issue. Could you assign this to me and guide to what changes you want. Thanks 😄

**Comment by ageddesi** [comment]
Hey @ahmedsilat44 no problem.

**Comment by ageddesi** [comment]
@ahmedsilat44 In the util file for getSpeciesOfAnimal you can see it returns a list of species, However this can turn out to not be a unique list, so the fix for this bug is to make sure it returns a unique list.

**Comment by ahmedsilat44** [comment]
> @ahmedsilat44 In the util file for getSpeciesOfAnimal you can see it returns a list of species, However this can turn out to not be a unique list, so the fix for this bug is to make sure it returns a unique list.

Ok so I went to the history of the file and there was this return 
return [...new Set(speciesList)]; 
would you like me to return this ?

**Comment by ageddesi** [comment]
That would be great, Thank you :) 
Nice quick win

**Comment by ageddesi** [comment]
Thanks so much @ahmedsilat44 . All the best and happy Hacktoberfest.
