### ISSUE TITLE
Error while starting the app

### ISSUE THREAD

**Issue by the-Shallow** [ageddesi/Mocked-API#201]
Here's the report: 
mocked-api-mocked-api-1  |
mocked-api-mocked-api-1  |
mocked-api-mocked-api-1  |  Error in ./modules/address/api/address-routes.ts :
mocked-api-mocked-api-1  | YAMLSemanticError: Plain value cannot start with a tab character at line 9, column 1:
mocked-api-mocked-api-1  |
mocked-api-mocked-api-1  |                 schema:
mocked-api-mocked-api-1  | ^^^^^^^^^^^
mocked-api-mocked-api-1  | ,Error in ./modules/address/api/address-routes.ts :
mocked-api-mocked-api-1  | YAMLSyntaxError: All collection items must start at the same column at line 3, column 5:
mocked-api-mocked-api-1  |
mocked-api-mocked-api-1  |     tags:
mocked-api-mocked-api-1  |     ^^^^^…
mocked-api-mocked-api-1  |
mocked-api-mocked-api-1  | YAMLSyntaxError: Failed to resolve SEQ_ITEM node here at line 11, column 6:
mocked-api-mocked-api-1  |
mocked-api-mocked-api-1  |      - name: qty
mocked-api-mocked-api-1  |      ^^^^^^^^^^^^…
mocked-api-mocked-api-1  |
mocked-api-mocked-api-1  | YAMLSemanticError: Implicit map keys need to be followed by map values at line 11, column 6:
mocked-api-mocked-api-1  |
mocked-api-mocked-api-1  |      - name: qty
mocked-api-mocked-api-1  |      ^^^^^^^^^^^^…
mocked-api-mocked-api-1  |
mocked-api-mocked-api-1  | YAMLSemanticError: Implicit map keys need to be on a single line at line 11, column 6:
mocked-api-mocked-api-1  |
mocked-api-mocked-api-1  |      - name: qty
mocked-api-mocked-api-1  |      ^^^^^^^^^^^^…

**Comment by devvspaces** [comment]
Yes its' yaml error

**Comment by devvspaces** [comment]
I am currently working on it

**Comment by ageddesi** [comment]
Thanks @devvspaces
