### ISSUE TITLE
[New Mock]: Movies/Films

### ISSUE THREAD

**Issue by devrrior** [ageddesi/Mocked-API#206]
An endpoint that returns a list of movies, each movie could have the following attributes:
- name
- description
- URL image
- release date
- director
- genres

If it's possible, I'd like to be assigned to this issue.

**Comment by ageddesi** [comment]
This could be fun, lets do it 👍, its yours.

**Comment by devrrior** [comment]
Is there a problem if I use static data? So that dynamic data is added by web scraping later on, as a new feature.

**Comment by ageddesi** [comment]
@devrrior for now static data is best. :)
