### ISSUE TITLE
News Api

### ISSUE THREAD

**Issue by mdmuaj13** [ageddesi/Mocked-API#218]
Hey there,
We can add tech news API. A news list and single news endpoint would be good enough for now. 

Each news object could have the following attributes:
```
- title
- slug
- summary
- published_date
- author
- category
- language
```

If it's possible, I'd like to be assigned to this issue.

**Comment by ageddesi** [comment]
hi @mdmuaj13,
I am happy for you to work on this.

**Comment by mdmuaj13** [comment]
thanks, @ageddesi. Can you mark it as **hacktoberfest** label?

**Comment by mdmuaj13** [comment]
@ageddesi PR submitted. 
#223
