### ISSUE TITLE
The 'Visit our Github' button is not working

### ISSUE THREAD

**Issue by NNL-Keerthana** [ageddesi/Mocked-API#219]
**The Bug**
The 'Visit our Github' button on the website is not working

![git1](https://user-images.githubusercontent.com/96995729/195989645-4b4ddfbc-6352-41bb-9ffb-3e7db3c0f0de.png)

**Comment by NNL-Keerthana** [comment]
I would like to fix this. Please assign it to me.

**Comment by sherlyfebrianti96** [comment]
I don't think it's related to this repository 🤔

**Comment by ageddesi** [comment]
Hi @NNL-Keerthana, thanks for raising this bug, I will take a look at this because as mentioned above this is not in this repo.

**Comment by ageddesi** [comment]
This is now fixed and deployed.
