### ISSUE TITLE
Add more details about a country to /country api

### ISSUE THREAD

**Issue by RizkyRajitha** [ageddesi/Mocked-API#229]
**Is your feature request related to a problem? Please describe.**
currently we get only an array of country name
![mokeapi](https://user-images.githubusercontent.com/38534289/196093344-078be56e-6090-4a56-ab4b-ed95e2a213da.png)

**Describe the solution you'd like**

return array of objects with country details

```json
"name": "Iceland",
"capital": "Reykjavik",
"continent":"Northern Europe",
"area":103000
```

Thank you

**Comment by ageddesi** [comment]
This would be a nice addition to the data.

**Comment by RizkyRajitha** [comment]
i will work on this @ageddesi
