### ISSUE TITLE
Chuck Norris Endpoint

### ISSUE THREAD

**Issue by computamike** [ageddesi/Mocked-API#236]
**Is your feature request related to a problem? Please describe.**
No - it's an endpoint suggestion.  Hitting the end point returns a random Chuck Norris fact.

**Describe the solution you'd like**
A Chuck Norris Fact Endpoint

**Describe alternatives you've considered**
There is no alternative to Chuck Norris - this is common Knowledge

**Additional context**
Here is a picture of Chuck Norris 
![image](https://user-images.githubusercontent.com/464876/196286237-c45cadbd-c315-4933-bb50-3ef49e950517.png)

**Comment by ageddesi** [comment]
Do it
