### ISSUE TITLE
Quantity specified as text returns 100 items

### ISSUE THREAD

**Issue by computamike** [ageddesi/Mocked-API#239]
**Describe the bug**
For some endpoints such as color (other end points may be affected) calling /colors/foo will return 100 colors.  This maybe should throw an exception, or return a single record.

**To Reproduce**
1. Start the server
2. Navigate to http://[localhost:3000/colors/1](http://localhost:3000/colors/1)
3. See that 1 record is returned
4. Navigate to http://[localhost:3000/colors/foo](http://localhost:3000/colors/foo)
5. See that 100 records are returned

**Expected behavior**
As the qty is not an integer, this should return an exception

**Screenshots**
![image](https://user-images.githubusercontent.com/464876/196538479-90248f2d-028c-4ce0-b900-55ce31087b83.png)
![image](https://user-images.githubusercontent.com/464876/196538706-f1b1b848-b228-41a6-bb81-fb2b51a5329c.png)

**Additional context
Asked by @ageddesi to raise this as part of #234

**Comment by ageddesi** [comment]
I have taken a look into this. Our flow logic for this function should be as follows. 

- Get qty from route,

- If there is no value then use the **defaultQty** in the class, however if the **overrideDefaultQty** has been provided in the util function call, set to this instead of **defaultQty**.

- If a value is present in the route, however is not a number it should be replaced with the default as specified above.

- finally what ever the result should be clamped to the **maxQty** allowed to be returned

**Comment by KidesLeo** [comment]
Seems pretty straightforward, I will get started working on it. Assignment appreciated.

**Comment by cweave** [comment]
> 

I think as a fail safe, there should be an error thrown if there isn't an `overrideDefaultQty` provided. I was messing with this last night with the route I added to try and add some error handling, but didn't want to go too far down the rabbit hole.

**Comment by KidesLeo** [comment]
> > * If there is no value then use the defaultQty in the class, however if the overrideDefaultQty has been provided in the util function call, set to this instead of defaultQty.
> > * If a value is present in the route, however is not a number it should be replaced with the default as specified above.
> 
> I think as a fail safe, there should be an error thrown if there isn't an `overrideDefaultQty` provided. I was messing with this last night with the route I added to try and add some error handling, but didn't want to go too far down the rabbit hole.
> 
> For example, give it a string, but don't provide a default. It makes the request ~100x.

Is that necessary? There is a const default quantity provided in [route-utils](https://github.com/ageddesi/Mocked-API/blob/dev/utils/route-utils.ts#L4).

**Comment by cweave** [comment]
> > > * If there is no value then use the defaultQty in the class, however if the overrideDefaultQty has been provided in the util function call, set to this instead of defaultQty.
> > > * If a value is present in the route, however is not a number it should be replaced with the default as specified above.
> > 
> > 
> > I think as a fail safe, there should be an error thrown if there isn't an `overrideDefaultQty` provided. I was messing with this last night with the route I added to try and add some error handling, but didn't want to go too far down the rabbit hole.
> > For example, give it a string, but don't provide a default. It makes the request ~100x.
> 
> Is that necessary? There is a const default quantity provided in [route-utils](https://github.com/ageddesi/Mocked-API/blob/dev/utils/route-utils.ts#L4).

Ah, that's my bad. I don't think I had the update when I was messing with it. So you're right, probably not necessary then :)
