### ISSUE TITLE
[New Mock]: BasketBall Teams

### ISSUE THREAD

**Issue by ade1705** [ageddesi/Mocked-API#253]
**Is your feature request related to a problem? Please describe.**
Feature to add an endpoint that returns a list of Basketball NBA teams similar to `/sports/football/leagues/premier/teams`

**Describe the solution you'd like**

Sample response would look like this
```json
  [{
    "abbr": "CHI",
    "conference": "Eastern",
    "division": "Central",
    "city": "Chicago",
    "name": "Bulls",
    "color": "CE1141",
    "colors": [
      "CE1141",
      "061922"
    ]
  }]

```
I'd like to be assigned to this issue.

**Comment by ageddesi** [comment]
This would be awesome :) @ade1705

**Comment by ade1705** [comment]
@ageddesi Please review
