### ISSUE TITLE
There seems to be 2 different swagger tags for currencies

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#258]
![image](https://user-images.githubusercontent.com/1301564/197335614-5b847322-ccaa-4b91-ad57-f31d7ea7aa72.png)

**Comment by mohdmulla** [comment]
Hi, Can i be assigned to this?

**Comment by Xavier577** [comment]
Can I help out with this?

**Comment by Xavier577** [comment]
oh appears I was too late
