### ISSUE TITLE
[New Mock]: Provinces

### ISSUE THREAD

**Issue by wavpro** [ageddesi/Mocked-API#262]
**Is your feature request related to a problem? Please describe.**
Feature to add ``/countries/provinces`` endpoint which returns a list of all countries and their provinces.

**Describe the solution you'd like**

Example response:
```json
{
  "Taiwan": [
    "Chang-hua",
    "Chia-i",
    "Hsin-chu",
    "Hua-lien",
    "I-lan",
    "Kao-hsiung",
    "Kin-men",
    "Lien-chiang",
    "Miao-li",
    "Nan-t'ou",
    "P'eng-hu",
    "P'ing-tung",
    "T'ai-chung",
    "T'ai-nan",
    "T'ai-pei",
    "T'ai-tung",
    "T'ao-yuan",
    "Yun-lin",
    "Chia-i",
    "Chi-lung",
    "Hsin-chu",
    "T'ai-chung",
    "T'ai-nan",
    "Kao-hsiung city",
    "T'ai-pei city"
  ]
}
```

**Comment by ageddesi** [comment]
This would be a great endpoint to add 👍

**Comment by wavpro** [comment]
I forgot to mention I wanted to work on it, I'll make a fork and start working on it.
