### ISSUE TITLE
[New Mock]: Courses 

### ISSUE THREAD

**Issue by edwardsmoses** [ageddesi/Mocked-API#265]
**Is your feature request related to a problem? Please describe.**
Adding an endpoint that returns a list of course similar to the e-commerce cart endpoint - `/ecommerce/cart` 

Describe the solution you'd like

A sample response would be something like this: 

```
  [{

    "name": "Introduction to Mocked-API",
    "description": "Learn best practices on how to use Mocked-API", 
    "provider": "Mocked-API Bootcamp",
    "url": "https://github.com/ageddesi/Mocked-API",
    "type": "virtual" //could also be physical
    "address":  ""Andrew Kappa\\n3686 Capital Lakeview\\nLahore 2344\\nUSA"", //when the course is of physical type
    "price":  900,
 }]
```

If it sounds good, I'll love to get on this later today - thanks!

**Comment by ageddesi** [comment]
Sounds like a great endpoint idea.
