### ISSUE TITLE
[New Mock]: Ligue 1 teams endpoint

### ISSUE THREAD

**Issue by ade1705** [ageddesi/Mocked-API#270]
Is your feature request related to a problem? Please describe.
Feature to add an endpoint that returns a list of Ligue 1 teams similar to /sports/football/leagues/premier/teams

Sample response would look like this

  ```json
[{
    "teamName": "Troyes",
    "location": "Troyes",
    "stadium": "Stade de l'Aube",
    "capacity": "21,684"
  }]
```

I'd like to be assigned to this issue.

**Comment by ageddesi** [comment]
This would be ace

**Comment by ade1705** [comment]
@ageddesi Please review
