### ISSUE TITLE
[Bug] Fixing Broken Links in Contributing Guidelines 

### ISSUE THREAD

**Issue by freshairr** [ageddesi/Mocked-API#271]
**Describe the bug**
There are several links in the contributing guidelines that lead to 404 errors. Mainly the documentation links, but also links to the bug tracker and a gif maker for Linux users  

**To Reproduce**
1. Go to https://github.com/ageddesi/Mocked-API/blob/dev/CONTRIBUTING.md
2. Click on any of the links from the screenshot below
3. See 404 error

**Expected behavior**
We expect the links to lead to the page in which the guidelines are describing

**Screenshots**
![Inkedmock1](https://user-images.githubusercontent.com/16641038/197577799-e9a948e5-cee1-4fbf-be81-8667b2341c00.jpg)
![Inkedmock2_LI](https://user-images.githubusercontent.com/16641038/197577801-fb807121-c63e-4f67-b28c-5c9b14e4eb16.jpg)
![Inkedmock3_LI](https://user-images.githubusercontent.com/16641038/197577804-c5a1c477-a97e-42af-9773-7e7feaf82311.jpg)
![Inkedmock4_LI](https://user-images.githubusercontent.com/16641038/197577805-a8c24f9d-3f2e-45fd-b3b8-fbee4d6ff301.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [106.0.1370.42]

**Additional context**
- I would like to update the docs link to match the readme and point it to: https://api.mocked-api.dev/
- It seems like byzanz for Linux has been archived and no longer update. I would propose updating the link to Peek, which is distributed on many official package repositories: https://github.com/phw/peek
- I would fix the broken url to the bug tracker link 
- And I would update all the "open an issue" links to point to this new url that has allows user to choose bug or feature and contains prefilled guidelines: https://github.com/ageddesi/Mocked-API/issues/new/choose

**Comment by ageddesi** [comment]
Thanks for finding all these issues :)

**Comment by freshairr** [comment]
Can I be assigned to this? Would like to start contributing :)
