### ISSUE TITLE
Documentation / CURL generated for Address is incorrect

### ISSUE THREAD

**Issue by computamike** [ageddesi/Mocked-API#274]
**Describe the bug**
The address endpoint - when executed through swagger, doesn't pass the parameters along.

**To Reproduce**
1. Start mockedAPI - in this instance I am running a local instance.
2. Click the address endpoint, click the try it out button
3. Enter uk as the country, and 3 as the qty
4. note that the request URL does not show the qty or country
5. note that the CURL command shown, also doesn't show the qty our country
![image](https://user-images.githubusercontent.com/464876/197646222-4a1c6347-5c78-4359-ba69-c3f66dbc9752.png)

6. Note that the results contain both zip code and postcode
![image](https://user-images.githubusercontent.com/464876/197646348-c67faf60-3e9a-4341-a43d-f92702de2572.png)

**Expected behavior**
It seems that there might be 2 bugs here:

- Swagger interface does not use the criteria collected from the user when executing the API call through swagger.
- If qty is not specified, 10 items are returned, and these addresses have both American and UK post / zip codes.

**Comment by mohdmulla** [comment]
Hi, @computamike I am interested in working on this issue, Please assign it to me if this issue still available?

**Comment by mohdmulla** [comment]
Hi @ageddesi  i would like to work on this issue, Can you assign it to me? Thanks.

**Comment by computamike** [comment]
Hi @mohdmulla  - I'm just a contributor so I can't assign bugs and stuff but if you can fix the problem then that would be great.
