### ISSUE TITLE
API Access from Swagger (CORS error) / 502 error

### ISSUE THREAD

**Issue by computamike** [ageddesi/Mocked-API#283]
**Describe the bug**
It seems that CORS configuration is preventing the production API site from serving API results to swagger front end, or a [sample codepen](https://codepen.io/cweave/pen/dyKPVVp)(thanks swampdolphin on discord).

**To Reproduce**
1. Go to [swagger](https://api.mocked-api.dev/)
2. Execute some of the endpoints
3. Get CORS error (occasionally?)
4. For a more consistent approach : try this [codepen](https://codepen.io/cweave/pen/dyKPVVp)
5. See error screenshot

**Expected behavior**
CORS errors should not probably be thrown when consuming the API from codepen

**Screenshots**
![image](https://user-images.githubusercontent.com/464876/198152275-a6be1cd6-dc0b-4d5e-90af-b3f1b016d12f.png)

**Additional context**
The stability of the API has been problematic - sometimes throwing a 502 error 
![image](https://user-images.githubusercontent.com/464876/198152600-9728b729-8178-4dd2-9c10-44dfd28cfb55.png)

**Comment by VaibhavGagneja** [comment]
Hi @computamike,
I have found the issue that is causing CORS in swagger, But as I can see the website https://api.mocked-api.dev/ is no longer functional should I raise pr for the fix?
— Vaibhav

**Comment by ageddesi** [comment]
Hi @VaibhavGagneja If you have the fix that would be most welcome. We are just trying to sort out a hosting provider at the moment.
