### ISSUE TITLE
Counts are wrong

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#300]
**Describe the bug**
We use the following data endpoint on the mocked-api.dev website to show the current api count. 
https://api.mocked-api.dev/full-status
Currently this count is wrong. I can see just over 30 categories in the codebase but the site only says 22. I also imagine the api endpoint count is incorrect also.

To fix this an Audit needs to be performed on all api routes to ensure they have a Category defined.

**To Reproduce**
1. Go tomocked-api.dev and see the counts and list of categories on the site

**Comment by HM-8** [comment]
Hi @ageddesi. I would like to work on this if it has not been taken yet.

**Comment by ageddesi** [comment]
Hi @HM-8 - 100%. If you need any help we have a discord channel. https://discord.gg/khjXVqrd

**Comment by ageddesi** [comment]
Hi @HM-8 Is this still something you would like to work on?

**Comment by HM-8** [comment]
Hi @ageddesi. Yes I would still like to work on this. I just had some other things to prioritize. Is there a specific date you want this done by?

**Comment by ageddesi** [comment]
Hi, no rush. i just was checking if individuals assigned to tickets still wanted to work on them. :)

**Comment by HM-8** [comment]
Oh okay😸

**Comment by VinayJariya** [comment]
Hi @ageddesi , I would like to work on this if it is not taken yet
