### ISSUE TITLE
Morgan reporting (and possibly other middlwares are not working)

### ISSUE THREAD

**Issue by computamike** [ageddesi/Mocked-API#306]
**Describe the bug**
Executing the code from the main dev branch, there is no logging provided by the [morgan](https://www.npmjs.com/package/morgan) middleware.

**To Reproduce**
1. Clone the latest dev branch to get the latest code (this issue was found on [c78b5ee](https://github.com/ageddesi/Mocked-API/commit/c78b5eeba2783c0c8d6b42f00a6ee947d970d1e7))
2. run the site using `npm run serve`
3. Launch `http://localhost:3000/`
4. notice the console running the site looks like this:
![image](https://user-images.githubusercontent.com/464876/203198762-36361e45-c83c-4936-8999-c0f0a639b082.png)
6. Move the line `app.use(morgan('combined')); // adding morgan to log HTTP requests` from line 61 to line 26.
7. The site will recompile.  Once this is done refresh the swagger page
8. Note that logging is now shown on the console.
![image](https://user-images.githubusercontent.com/464876/203199057-82ffd030-480c-418f-9e05-9e5527967b0e.png)

**Expected behaviour**
Logging should be showing for each request - however due to the API endpoints ending the middleware change, any middleware that is chained like this, that is defined after the API routes won't execute.

**Additional context**
The resolution to this would be (I would suggest) to define all of the middleware first, then register the API (and other) end points.

**Comment by ageddesi** [comment]
This is a good shout @computamike Will look into this.
