### ISSUE TITLE
Add new Nutrition endpoint

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#310]
Add a new endpoint for nutrition. We can start with fruit which I have added below.

Endpoints: 

```
/food/nutrition/fruits/
/food/nutrition/fruits/:qty
```

![image](https://user-images.githubusercontent.com/1301564/204472603-07d558d1-4463-458d-a4f6-5df9d5d3fc37.png)

**Comment by GauravRanganath** [comment]
Hi @ageddesi! I'm gauravitude from the discord server, could you please assign this issue to me?

**Comment by ageddesi** [comment]
All yours @GauravRanganath

**Comment by Eric-R-Liang** [comment]
Hey @ageddesi, the data we are using is from Government of Canada's Canadian Nutrient File (CNF). Following is a link to the website: https://www.canada.ca/en/health-canada/services/food-nutrition/healthy-eating/nutrient-data/canadian-nutrient-file-2015-download-files.html.
