### ISSUE TITLE
Setup a prettier and eslint pre-commit hook

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#32]
This will make sure to enforce our coding standards.

**Comment by utsav00** [comment]
I'd like to take this up

**Comment by ageddesi** [comment]
It is yours, please branch from v.0.12.0

**Comment by utsav00** [comment]
I was checking the linter configs out and tried running it. Observed that it is not setup correctly right now. Am I mistaken or should I fix it and push it?
In case of the latter option, shall I push this with the current PR or address it with a new issue?

**Comment by ageddesi** [comment]
If you could fix it so it is setup correctly that would also be amazing :P

**Comment by utsav00** [comment]
Sure. Then I'll push with the same PR

**Comment by utsav00** [comment]
Thank you for your patience. Awaiting review
