### ISSUE TITLE
Upgrade astro to v3

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#347]
Astro has now released V3, It would be great to get the marketing site upgraded to include this.

**Comment by PalaniappanC** [comment]
I would like to work on this. Kindly assign this issue to my name

**Comment by ageddesi** [comment]
100% its yours.

**Comment by ageddesi** [comment]
100% its yours.

**Comment by PalaniappanC** [comment]
#350

**Comment by ageddesi** [comment]
@all-contributors please add @PalaniappanC for code
