### ISSUE TITLE
Blog Post: How to use an api in Angular

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#348]
Add a blog post using markdown that shows someone how to use one of our APIs to show and interact with mocked data using the library Angular.

**Comment by JOSHI53** [comment]
Hey, Can I work on this?

**Comment by shodown96** [comment]
I would like to work on this

**Comment by shodown96** [comment]
So close😭😅

**Comment by JOSHI53** [comment]
> So close😭😅

You can work on this no worries 🤣, I would take my request back. Good Luck

**Comment by shodown96** [comment]
Ayye, thank you so much man😅

**Comment by shodown96** [comment]
Hello @ageddesi, I would love to work on this.

**Comment by ageddesi** [comment]
Hi @shodown96 Happy for you to pick this up
