### ISSUE TITLE
Configuration of the root endpoint to be more welcoming

### ISSUE THREAD

**Issue by shodown96** [ageddesi/Mocked-API#351]
I successfully started the server application currently listening at port 3000, I followed the root endpoint, and the first thing I saw was an error page saying `Cannot GET /`. 

So this isn't a bug or issue that needs fixing but I feel if this application is going to be used by developers, it should display a welcoming message and possibly a sample endpoint to test or visit. This would also help people who for some reason don't access the swagger documentation first. An alternative would be to map the swagger documentation to the root endpoint.

This is a very simple task and I could easily fix it, I would like to be assigned if accepted. Thank you.

**Comment by ageddesi** [comment]
Hi @shodown96 I would like it if the swagger doc was routed at that initial /GET.
Happy for you to work on this 👍
