### ISSUE TITLE
Add jest to enable testing of endpoints and utils

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#4]
Add unit tests I to the app to test util files and api endpoints.

**Comment by Sir-Martin-Esq-III** [comment]
Hey, I'd like to pick this up if possible.

**Comment by ageddesi** [comment]
Hey @Sir-Martin-Esq-III This is yours. 
The only requirement I would have is that each module can have its own test folder. 
Thank you. 👍

**Comment by ageddesi** [comment]
Brilliant. That's what we wanted. Feel free to make a note of them in a ticket and mark as skip like you say. Then we can come back and fix them. 

Appreciate the hard work.
