### ISSUE TITLE
Improve Chat Message endpoints to include the users

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#45]
**Is your feature request related to a problem? Please describe.**
When you get the current list of messages back, we can not display a user friendly name or even a user profile image as we do not send back the list of users that we have generated.

**Describe the solution you'd like**
Split the return of the endpoint modal to the following 
```
{
 users: [], // A list of the users and their data.
 message: [] // A list of the messages
}
```

**Comment by YasiOnFire** [comment]
Hi, may I work on this one?

**Comment by ageddesi** [comment]
Hey @YasiOnFire I would love you to contribute. Go for it :)

**Comment by ageddesi** [comment]
Thanks @YasiOnFire for the contribution.
