### ISSUE TITLE
Update contributing guide with steps to add an api endpoint

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#46]
1. How to add an endpoint
2. How our folders are structured
3. How to add tests
4. How to add OpenAPI comments

**Comment by bpvcode** [comment]
Hello,

Can I work on this issue?
Can you assign this to me?

Thanks :)

**Comment by ageddesi** [comment]
Hi @bpvcode This is all yours :) welcome to the party.
