### ISSUE TITLE
Update readme with guide to running the app

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#47]

**Comment by alberturria** [comment]
Hey @ageddesi could I work on this one? 
I've seen that you already have a 'Getting started' section in your `Readme`, would you add this doc to that section?

**Comment by ageddesi** [comment]
Hey @alberturria This is yours :)

**Comment by ageddesi** [comment]
Thanks so much @alberturria for the contribution. Happy Hacktoberfest

**Comment by alberturria** [comment]
Thanks to you @ageddesi !!
