### ISSUE TITLE
[New Mock] - Product

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#48]
Using a variety of helpers in faker and our own util methods create a endpoint for getting a qty of mocked products. 

Faker starting point https://fakerjs.dev/api/commerce.html#color

**Comment by Trigstur** [comment]
I’d love to try and implement this

**Comment by ageddesi** [comment]
This is yours :)

**Comment by ageddesi** [comment]
Thanks @Trigstur for the awesome work on this. Happy Hacktoberfest
