### ISSUE TITLE
[New Mock] - Address

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#5]
See for data: https://fakerjs.dev/api/address.html

**Comment by zaibugemi** [comment]
@ageddesi I would like to take this on. Can you share what address details you would like to be returned from the endpoint? Also, do we want only a single endpoint that would return a random address detail?

**Comment by ageddesi** [comment]
Hi @zaibugemi thank you. I would to start off with mock addresses for the UK format and the USA format.
