### ISSUE TITLE
[New Mock] : Bank Feed

### ISSUE THREAD

**Issue by ageddesi** [ageddesi/Mocked-API#64]
The user should be able to hit an endpoint that returns them a fake bank feed.

**Comment by siddharth1729** [comment]
Hii  @ageddesi 

What i can understand is that i have to make and endpoint  "/bank_feed" , and it will return a json of bank feed ?

what will be the json of bank feed and all is that i have to decide or it will be dummy stuff 

pleas help me with this isuu i want to contribute for hacktober 2022

**Comment by ageddesi** [comment]
Hi @siddharth1729 

This is correct, we need a new api endpoint 

/bank/feed/

with some dummy data such as an 

```
 - bank accounts number
 - sort code
 - iban number
 - statement (array of items that appear on a statement)
```

**Comment by siddharth1729** [comment]
Hii @ageddesi 

I have forked this repo and implemented this specfic api do let me know if any chnges in that api as i have imlemented in my own way as i use to write api in my company

**Comment by ageddesi** [comment]
Awesome @siddharth1729, please raise a PR to branch v.0.13.0 when you are ready. I will be reviewing the next batch of PRs tomorrow

**Comment by siddharth1729** [comment]
@ageddesi i have created a pull request please check and if not lt me now i will o it again
