### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by kalwabed** [ageddesi/Mocked-API#75]
**Is your feature request related to a problem? Please describe.**
I struggle with formatting in this project with my existing Prettier (vscode) config.

**Describe the solution you'd like**
I think it would be great to have a Prettier configuration for this project, so we can go forward without worrying about formatting.

**Comment by kalwabed** [comment]
Sorry, I'm usually using `.prettierrc` file, didn't see that config file (`.prettierrc.json`).

**Comment by ageddesi** [comment]
Hi @kalwabed, thanks for the message. there is a ticket someone is working on to add a git pre hook to make sure it is run before pushes.
