### ISSUE TITLE
Adding News Feature 

### ISSUE THREAD

**Issue by DevilzzNikhil** [ageddesi/Mocked-API#81]
We can Add feature of showing Fake Email Address with the name provided by the user @ageddesi

**Comment by ageddesi** [comment]
Hi @DevilzzNikhil adding a new endpoint for this would be a nice idea. :)

**Comment by siddharth1729** [comment]
@ageddesi @DevilzzNikhil 
Please do let me know more about this issue i want t work on this

**Comment by ageddesi** [comment]
@DevilzzNikhil 
Are we saying a new endpoint, where the user can provide the first name or the first and second name and the end point adds a @domain.com etc to the name?

**Comment by siddharth1729** [comment]
@ageddesi 
Ok i can write a function that takes 2 argument and then returns a concatination string like a real mail ?

Am i right ?

**Comment by DevilzzNikhil** [comment]
@ageddesi  yes you got it right 
like if user provide mohit and sharma then email will return fake email like 
sharmaMohit@xyz.com
Should i work on these or think og something else

**Comment by ageddesi** [comment]
@DevilzzNikhil you can work on this as you were first on the ticket. :)

**Comment by GuillaumeGayot** [comment]
@ageddesi I am ready to work on this, as @DevilzzNikhil didn't open a PR yet and the hacktober fest end in a week

**Comment by ageddesi** [comment]
Go for it pal :)

**Comment by sergejomon** [comment]
Done !
