### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by cmjchrisjones** [ageddesi/Mocked-API#83]
The ability to run the project inside a docker container so that Node/NPM isn't required as a pre-requisite, and you have an isolated development environment. The only pre-requisite that would be required would be Docker.

[blog](https://auth0.com/blog/use-docker-to-create-a-node-development-environment/) with more information about the benefits of using Docker

**Comment by ish-u** [comment]
Hello,
I would like to take this Issue. 
I just have to create a docker-compose.yml file with the necessary configuration to start a container right ?

**Comment by ageddesi** [comment]
Hi @ish-u there is already a PR in for this issue.

**Comment by ish-u** [comment]
yeah sorry
