### ISSUE TITLE
Adding Movies rating data

### ISSUE THREAD

**Issue by saimaheshtaduri** [ageddesi/Mocked-API#95]
**Is your feature request related to a problem? Please describe.**
API with a bunch of movie related content is useful and can also be used as a valid data for recommendation systems too. 

**Describe the solution you'd like**
I could be better if it's about movie, rating and other information

**Comment by ageddesi** [comment]
This could be a lot of fun, do you have an idea of the endpoints and the info that they will return

**Comment by saimaheshtaduri** [comment]
I can start my research if you could assign to me as part of hacktoberfest. @ageddesi

**Comment by ageddesi** [comment]
Its all yours :) 👍

**Comment by ageddesi** [comment]
Hi @saimaheshtaduri Is this something you would still like to work on?

**Comment by ageddesi** [comment]
Removing @saimaheshtaduri from the assignee due to inactivity
